name: Run event resolver script

on:
  schedule:
    - cron: "*/15 * * * *"

  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4.7.0
        with:
          python-version: '3.10'

      - name: Run python script
        run: |
          python -m pip install requests
          python upcoming-events/upcoming_resolver.py

      - name: Commit and push results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add upcomings.txt
          git commit -m "Add results"
          git push
